name: Golang tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.9'
    - run: go test -coverprofile=coverage.out -covermode=count ./...
    - run: go tool cover -func=coverage.out
